"""Anthropic Messages API compatibility layer for GibberishLM.

Implements just enough of the Anthropic `/v1/messages` wire protocol that the
official Claude Code CLI (which talks to whatever `ANTHROPIC_BASE_URL` points
at) will accept GibberishLM as its "model" and render streamed, entirely fake
output: reasoning ("thinking"), prose, and tool calls.

Nothing here is a real model. Every response is fabricated nonsense.
"""

from __future__ import annotations

import json
import random
import uuid
from dataclasses import dataclass
from typing import Iterator, List, Tuple

import gibberishlm


def _evt(event: str, data: dict) -> str:
    """Format one Anthropic-style SSE message."""
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


def _msg_id() -> str:
    return "msg_" + uuid.uuid4().hex[:24]


def _tool_id() -> str:
    return "toolu_" + uuid.uuid4().hex[:24]


def _fake_signature() -> str:
    return uuid.uuid4().hex + uuid.uuid4().hex


def _request_has_tool_result(messages: List[dict]) -> bool:
    """True if the latest user turn contains a tool_result."""
    for message in reversed(messages):
        if message.get("role") != "user":
            continue
        content = message.get("content")
        return isinstance(content, list) and any(
            isinstance(block, dict) and block.get("type") == "tool_result"
            for block in content
        )
    return False


def _demo_tool_input(tool: dict) -> dict | None:
    """Return safe demo input for a supported tool offered by the client."""
    name = tool.get("name", "").lower()
    if name == "bash":
        return {
            "command": random.choice(gibberishlm.FAKE_COMMANDS),
            "description": "Run a safe GibberishLM demo command",
        }
    if name in ("list_bash", "list_agents"):
        return {}
    if name == "glob":
        return {"pattern": "*"}
    if name in ("grep", "rg"):
        return {"pattern": "lorem", "output_mode": "files_with_matches"}
    if name == "sql":
        return {"description": "Run demo query", "query": "SELECT 1"}
    return None


def _select_supported_tool(tools: List[dict]) -> tuple[str, dict] | None:
    supported = []
    for tool in tools or []:
        if not isinstance(tool, dict) or not tool.get("name"):
            continue
        tool_input = _demo_tool_input(tool)
        if tool_input is not None:
            supported.append((tool["name"], tool_input))
    return supported[random.randrange(len(supported))] if supported else None


def plan_blocks(
    messages: List[dict],
    tools: List[dict],
    want_thinking: bool,
    allow_tools: bool,
    think_words: int = 0,
) -> List[dict]:
    """Decide the content blocks for this response.

    Returns a list of light dicts describing each block to stream. The actual
    text is generated by the gibberishlm engine. ``think_words`` sizes the
    reasoning block so its streaming duration matches a sampled time budget.
    """
    blocks: List[dict] = []
    continuation = _request_has_tool_result(messages)
    selected_tool = _select_supported_tool(tools)

    # Reasoning block (only when the client asked for extended thinking, and
    # only on a fresh turn — keeps the agent loop short and predictable).
    if want_thinking and not continuation:
        blocks.append({"type": "thinking",
                       "text": gibberishlm.thinking_text(think_words // 2)})

    # Assistant prose.
    blocks.append({"type": "text", "text": gibberishlm._paragraph(1, 2)})

    # Drive one safe tool offered by the client on each fresh turn. A
    # continuation never emits another tool, avoiding endless tool loops.
    if allow_tools and not continuation and selected_tool is not None:
        tool_name, tool_input = selected_tool
        blocks.append(
            {
                "type": "tool_use",
                "id": _tool_id(),
                "name": tool_name,
                "input": tool_input,
            }
        )

    return blocks


def estimate_input_tokens(messages: List[dict]) -> int:
    """Use the same rough input estimate for messages and count_tokens."""
    return max(1, len(json.dumps(messages)) // 4)


def estimate_output_tokens(block: dict) -> int:
    """Estimate tokens from emitted text or a complete tool-use block."""
    if block["type"] in ("thinking", "text"):
        content = block["text"]
    else:
        content = json.dumps(
            {key: block[key] for key in ("type", "id", "name", "input")},
            sort_keys=True,
        )
    return (len(content) + 3) // 4


@dataclass(frozen=True)
class ResponsePlan:
    blocks: tuple[dict, ...]
    stop_reason: str
    input_tokens: int
    output_tokens: int


def prepare_response(
    messages: List[dict], blocks: List[dict], max_tokens: int | None = None
) -> ResponsePlan:
    """Bound generated content before either JSON or SSE serialization."""
    emitted = []
    remaining = max_tokens
    cut_short = False
    for block in blocks:
        tokens = estimate_output_tokens(block)
        if remaining is not None and tokens > remaining:
            if block["type"] in ("thinking", "text") and remaining > 0:
                emitted.append({**block, "text": block["text"][:remaining * 4]})
            cut_short = True
            break
        emitted.append(block.copy())
        if remaining is not None:
            remaining -= tokens

    for block in emitted:
        if block["type"] == "thinking":
            block["signature"] = _fake_signature()

    return ResponsePlan(
        blocks=tuple(emitted),
        stop_reason=("max_tokens" if cut_short else
                     "tool_use" if any(b["type"] == "tool_use" for b in emitted)
                     else "end_turn"),
        input_tokens=estimate_input_tokens(messages),
        output_tokens=sum(estimate_output_tokens(block) for block in emitted),
    )


def _stream_text_block(
    index: int, block: dict, timing
) -> Iterator[Tuple[float, str]]:
    """Yield (delay, sse) events for a thinking or text content block."""
    kind, text = block["type"], block["text"]
    if kind == "thinking":
        yield (0.0, _evt(
            "content_block_start",
            {"type": "content_block_start", "index": index,
             "content_block": {"type": "thinking", "thinking": ""}}))
        delta_type, field = "thinking_delta", "thinking"
    else:
        yield (0.0, _evt(
            "content_block_start",
            {"type": "content_block_start", "index": index,
             "content_block": {"type": "text", "text": ""}}))
        delta_type, field = "text_delta", "text"

    words = text.split(" ")
    for i in range(0, len(words), 2):
        chunk = " ".join(words[i:i + 2])
        if i + 2 < len(words):
            chunk += " "
        wc = max(1, len(chunk.split()))
        delay = (timing.think_delay(wc) if kind == "thinking"
                 else timing.text_delay(wc))
        yield (delay, _evt(
            "content_block_delta",
            {"type": "content_block_delta", "index": index,
             "delta": {"type": delta_type, field: chunk}}))

    if kind == "thinking":
        yield (0.0, _evt(
            "content_block_delta",
            {"type": "content_block_delta", "index": index,
             "delta": {"type": "signature_delta", "signature": block["signature"]}}))

    yield (0.0, _evt("content_block_stop",
                     {"type": "content_block_stop", "index": index}))


def _stream_tool_block(index: int, block: dict, timing) -> Iterator[Tuple[float, str]]:
    """Yield (delay, sse) events for a tool_use content block."""
    yield (0.0, _evt(
        "content_block_start",
        {"type": "content_block_start", "index": index,
         "content_block": {"type": "tool_use", "id": block["id"],
                           "name": block["name"], "input": {}}}))
    payload = json.dumps(block["input"])
    # Split the JSON into a couple of partial_json deltas for realism.
    mid = max(1, len(payload) // 2)
    for part in (payload[:mid], payload[mid:]):
        yield (timing.tool_delay(2), _evt(
            "content_block_delta",
            {"type": "content_block_delta", "index": index,
             "delta": {"type": "input_json_delta", "partial_json": part}}))
    yield (0.0, _evt("content_block_stop",
                     {"type": "content_block_stop", "index": index}))


def stream_messages(
    model: str,
    response_plan: ResponsePlan,
    timing,
) -> Iterator[Tuple[float, str]]:
    """Yield (delay, sse) tuples for a full Anthropic streaming response.

    ``delay`` is the number of seconds the caller should sleep *before*
    emitting the accompanying SSE text, so the stream is paced like a real,
    deliberate frontier model.
    """
    message_id = _msg_id()

    yield (0.0, _evt(
        "message_start",
        {"type": "message_start",
         "message": {"id": message_id, "type": "message", "role": "assistant",
                     "model": model, "content": [],
                     "stop_reason": None, "stop_sequence": None,
                     "usage": {"input_tokens": response_plan.input_tokens,
                               "output_tokens": 0}}}))

    has_visible_thinking = any(
        b["type"] == "thinking" for b in response_plan.blocks
    )
    initial_delay = timing.initial_delay(has_visible_thinking)

    for index, block in enumerate(response_plan.blocks):
        if block["type"] == "tool_use":
            events = _stream_tool_block(index, block, timing)
        else:
            events = _stream_text_block(index, block, timing)

        for j, (delay, sse) in enumerate(events):
            # The very first event of the response carries the time-to-first
            # -token latency (model "spin-up" / silent deliberation).
            if index == 0 and j == 0:
                delay = initial_delay
            yield (delay, sse)

        # A ping between blocks, like the real API.
        yield (0.0, _evt("ping", {"type": "ping"}))

    yield (0.0, _evt(
        "message_delta",
        {"type": "message_delta",
         "delta": {"stop_reason": response_plan.stop_reason,
                   "stop_sequence": None},
         "usage": {"output_tokens": response_plan.output_tokens}}))
    yield (0.0, _evt("message_stop", {"type": "message_stop"}))


def build_nonstreaming_response(model: str, response_plan: ResponsePlan) -> dict:
    """Build a complete (non-streaming) Anthropic Messages response body."""
    content = []
    for block in response_plan.blocks:
        if block["type"] == "thinking":
            content.append({"type": "thinking", "thinking": block["text"],
                            "signature": block["signature"]})
        elif block["type"] == "text":
            content.append({"type": "text", "text": block["text"]})
        elif block["type"] == "tool_use":
            content.append({"type": "tool_use", "id": block["id"],
                            "name": block["name"], "input": block["input"]})
    return {
        "id": _msg_id(),
        "type": "message",
        "role": "assistant",
        "model": model,
        "content": content,
        "stop_reason": response_plan.stop_reason,
        "stop_sequence": None,
        "usage": {"input_tokens": response_plan.input_tokens,
                  "output_tokens": response_plan.output_tokens},
    }
