"""Anthropic Messages API compatibility layer for LoremOpus.

Implements just enough of the Anthropic `/v1/messages` wire protocol that the
official Claude Code CLI (which talks to whatever `ANTHROPIC_BASE_URL` points
at) will accept LoremOpus as its "model" and render streamed, entirely fake
output: reasoning ("thinking"), prose, and Bash tool calls.

Nothing here is a real model. Every response is fabricated nonsense.
"""

from __future__ import annotations

import json
import random
import uuid
from typing import Iterator, List, Tuple

import loremopus


def _evt(event: str, data: dict) -> str:
    """Format one Anthropic-style SSE message."""
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


def _msg_id() -> str:
    return "msg_" + uuid.uuid4().hex[:24]


def _tool_id() -> str:
    return "toolu_" + uuid.uuid4().hex[:24]


def _fake_signature() -> str:
    return uuid.uuid4().hex + uuid.uuid4().hex


def _request_has_tool_result(messages: List[dict]) -> bool:
    """True if the latest user turn contains a tool_result."""
    for message in reversed(messages):
        if message.get("role") != "user":
            continue
        content = message.get("content")
        return isinstance(content, list) and any(
            isinstance(block, dict) and block.get("type") == "tool_result"
            for block in content
        )
    return False


def _available_tool_names(tools: List[dict]) -> set:
    names = set()
    for tool in tools or []:
        name = tool.get("name") if isinstance(tool, dict) else None
        if name:
            names.add(name)
    return names


def plan_blocks(
    messages: List[dict],
    tools: List[dict],
    want_thinking: bool,
    allow_tools: bool,
    think_words: int = 0,
) -> List[dict]:
    """Decide the content blocks for this response.

    Returns a list of light dicts describing each block to stream. The actual
    text is generated by the loremopus engine. ``think_words`` sizes the
    reasoning block so its streaming duration matches a sampled time budget.
    """
    blocks: List[dict] = []
    continuation = _request_has_tool_result(messages)
    tool_names = _available_tool_names(tools)

    # Reasoning block (only when the client asked for extended thinking, and
    # only on a fresh turn — keeps the agent loop short and predictable).
    if want_thinking and not continuation:
        blocks.append({"type": "thinking",
                       "text": loremopus.thinking_text(think_words)})

    # Assistant prose.
    blocks.append({"type": "text", "text": loremopus._paragraph(2, 4)})

    # Optionally drive a single Bash tool call so the CLI demonstrates an
    # "action". Only do this if the CLI actually offers a Bash tool and we are
    # not already mid-loop (avoids endless tool/tool_result ping-pong).
    if (
        allow_tools
        and not continuation
        and "Bash" in tool_names
        and random.random() < 0.7
    ):
        command = random.choice(loremopus.FAKE_COMMANDS)
        blocks.append(
            {
                "type": "tool_use",
                "id": _tool_id(),
                "name": "Bash",
                "input": {
                    "command": command,
                    "description": "LoremOpus demo command (fake)",
                },
            }
        )

    return blocks


def _stream_text_block(index: int, kind: str, text: str, timing) -> Iterator[Tuple[float, str]]:
    """Yield (delay, sse) events for a thinking or text content block."""
    if kind == "thinking":
        yield (0.0, _evt(
            "content_block_start",
            {"type": "content_block_start", "index": index,
             "content_block": {"type": "thinking", "thinking": ""}}))
        delta_type, field = "thinking_delta", "thinking"
    else:
        yield (0.0, _evt(
            "content_block_start",
            {"type": "content_block_start", "index": index,
             "content_block": {"type": "text", "text": ""}}))
        delta_type, field = "text_delta", "text"

    words = text.split(" ")
    for i in range(0, len(words), 2):
        chunk = " ".join(words[i:i + 2])
        if i + 2 < len(words):
            chunk += " "
        wc = max(1, len(chunk.split()))
        delay = (timing.think_delay(wc) if kind == "thinking"
                 else timing.text_delay(wc))
        yield (delay, _evt(
            "content_block_delta",
            {"type": "content_block_delta", "index": index,
             "delta": {"type": delta_type, field: chunk}}))

    if kind == "thinking":
        yield (0.0, _evt(
            "content_block_delta",
            {"type": "content_block_delta", "index": index,
             "delta": {"type": "signature_delta", "signature": _fake_signature()}}))

    yield (0.0, _evt("content_block_stop",
                     {"type": "content_block_stop", "index": index}))


def _stream_tool_block(index: int, block: dict, timing) -> Iterator[Tuple[float, str]]:
    """Yield (delay, sse) events for a tool_use content block."""
    yield (0.0, _evt(
        "content_block_start",
        {"type": "content_block_start", "index": index,
         "content_block": {"type": "tool_use", "id": block["id"],
                           "name": block["name"], "input": {}}}))
    payload = json.dumps(block["input"])
    # Split the JSON into a couple of partial_json deltas for realism.
    mid = max(1, len(payload) // 2)
    for part in (payload[:mid], payload[mid:]):
        yield (timing.tool_delay(2), _evt(
            "content_block_delta",
            {"type": "content_block_delta", "index": index,
             "delta": {"type": "input_json_delta", "partial_json": part}}))
    yield (0.0, _evt("content_block_stop",
                     {"type": "content_block_stop", "index": index}))


def stream_messages(
    model: str,
    blocks: List[dict],
    timing,
) -> Iterator[Tuple[float, str]]:
    """Yield (delay, sse) tuples for a full Anthropic streaming response.

    ``delay`` is the number of seconds the caller should sleep *before*
    emitting the accompanying SSE text, so the stream is paced like a real,
    deliberate frontier model.
    """
    message_id = _msg_id()
    input_tokens = random.randint(8, 64)

    yield (0.0, _evt(
        "message_start",
        {"type": "message_start",
         "message": {"id": message_id, "type": "message", "role": "assistant",
                     "model": model, "content": [],
                     "stop_reason": None, "stop_sequence": None,
                     "usage": {"input_tokens": input_tokens, "output_tokens": 1}}}))

    has_visible_thinking = any(b["type"] == "thinking" for b in blocks)
    initial_delay = timing.initial_delay(has_visible_thinking)

    has_tool_use = False
    for index, block in enumerate(blocks):
        if block["type"] == "tool_use":
            has_tool_use = True
            events = _stream_tool_block(index, block, timing)
        else:
            events = _stream_text_block(index, block["type"], block["text"], timing)

        for j, (delay, sse) in enumerate(events):
            # The very first event of the response carries the time-to-first
            # -token latency (model "spin-up" / silent deliberation).
            if index == 0 and j == 0:
                delay = initial_delay
            yield (delay, sse)

        # A ping between blocks, like the real API.
        yield (0.0, _evt("ping", {"type": "ping"}))

    stop_reason = "tool_use" if has_tool_use else "end_turn"
    output_tokens = random.randint(20, 220)

    yield (0.0, _evt(
        "message_delta",
        {"type": "message_delta",
         "delta": {"stop_reason": stop_reason, "stop_sequence": None},
         "usage": {"output_tokens": output_tokens}}))
    yield (0.0, _evt("message_stop", {"type": "message_stop"}))


def build_nonstreaming_response(model: str, blocks: List[dict]) -> dict:
    """Build a complete (non-streaming) Anthropic Messages response body."""
    content = []
    has_tool_use = False
    for block in blocks:
        if block["type"] == "thinking":
            content.append({"type": "thinking", "thinking": block["text"],
                            "signature": _fake_signature()})
        elif block["type"] == "text":
            content.append({"type": "text", "text": block["text"]})
        elif block["type"] == "tool_use":
            has_tool_use = True
            content.append({"type": "tool_use", "id": block["id"],
                            "name": block["name"], "input": block["input"]})
    return {
        "id": _msg_id(),
        "type": "message",
        "role": "assistant",
        "model": model,
        "content": content,
        "stop_reason": "tool_use" if has_tool_use else "end_turn",
        "stop_sequence": None,
        "usage": {"input_tokens": random.randint(8, 64),
                  "output_tokens": random.randint(20, 220)},
    }
